수정 후 재실행: 첫 실행의 N28 지정상품 범위 회귀를 보존하고 등록 상품명 바로 앞 발급사 문맥만 복구했다. 기존 32개와 상품 문맥 3개 회귀 검사를 통과한 뒤 재검색한다. 최초 실행은 `data/64_scope_boundary_comparison_initial_run/`에 보존한다. 임베딩·동일 재정렬 점수를 재사용하므로 이 실행 시간을 신규 운영 질문의 응답시간으로 해석하지 않는다.

# 64 · 범위 수정과 구조화 추가 효과 분리

benefit과parent-child는각자기존선택프로필로고정한다. 재정렬·가중치·청킹·묶음·답변지시를조정하지않는다. 계획은`notes/63_65_fixed_profile_structured_addition_plan.md`다.

긴API실행과원문판정사이에중단·재개가필요하므로기존raw-provider저널을재사용하는공통helper만scripts에두었다. 결과HTML은실제결과확인후직접작성하며생성script를사용하지않는다.

원문확인단계마다저장후아래다음셀을실행한다. 캐시복사시간과새호출시간을구분하고누적8달러를유지한다.

In [1]:
from pathlib import Path
import importlib.util,sys,json
ROOT=Path.cwd() if (Path.cwd()/'notebooks').is_dir() else Path.cwd().parent
spec=importlib.util.spec_from_file_location('fixed_profile_runtime',ROOT/'notebooks/scripts/63_65_experiment_runtime.py')
R=importlib.util.module_from_spec(spec);sys.modules[spec.name]=R;spec.loader.exec_module(R)
queries,manifest=R.prepare(64,ROOT/'notebooks/64_scope_boundary_comparison.ipynb')
print('단계',manifest['stage'],'질문',len(queries),'누적보수차감',R.X.budget_upper_ledger()['known_cost_usd'])

단계 64 질문 40 누적보수차감 1.289768890

In [2]:
resources=R.run64(queries,manifest,allow_network=True)
print(resources)

/home/sms/miniconda3/envs/skn25/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

64 search 1 / 40 rows 24

64 search 2 / 40 rows 48

64 search 3 / 40 rows 72

64 search 4 / 40 rows 96

64 search 5 / 40 rows 120

64 search 6 / 40 rows 144

64 search 7 / 40 rows 168

64 search 8 / 40 rows 192

64 search 9 / 40 rows 216

64 search 10 / 40 rows 240

64 search 11 / 40 rows 264

64 search 12 / 40 rows 288

64 search 13 / 40 rows 312

64 search 14 / 40 rows 336

64 search 15 / 40 rows 360

64 search 16 / 40 rows 384

64 search 17 / 40 rows 408

64 search 18 / 40 rows 432

64 search 19 / 40 rows 456

64 search 20 / 40 rows 480

64 search 21 / 40 rows 504

64 search 22 / 40 rows 528

64 search 23 / 40 rows 552

64 search 24 / 40 rows 576

64 search 25 / 40 rows 600

64 search 26 / 40 rows 624

64 search 27 / 40 rows 648

64 search 28 / 40 rows 672

64 search 29 / 40 rows 696

64 search 30 / 40 rows 720

64 search 31 / 40 rows 744

64 search 32 / 40 rows 768

64 search 33 / 40 rows 792

64 search 34 / 40 rows 816

64 search 35 / 40 rows 840

64 search 36 / 40 rows 864

64 search 37 / 40 rows 888

64 search 38 / 40 rows 912

64 search 39 / 40 rows 936

64 search 40 / 40 rows 960

64 boundary 1 / 8 rows 8

64 boundary 2 / 8 rows 16

64 boundary 3 / 8 rows 24

64 boundary 4 / 8 rows 32

64 boundary 5 / 8 rows 40

64 boundary 6 / 8 rows 48

64 boundary 7 / 8 rows 56

64 boundary 8 / 8 rows 64

{'development_rows': 960, 'boundary_rows': 64, 'status': 'awaiting_source_and_independent_acceptance', 'price': {'record_count': 1, 'known_priced_records': 1, 'unknown_cost_records': 0, 'duplicate_saved_responses': 0, 'known_cost_usd': '0.0000035', 'tokens': {'input_tokens': 0, 'output_tokens': 0, 'ordinary_input_tokens': 0, 'cached_input_tokens': 0, 'cache_write_tokens': 0, 'embedding_tokens': 175}, 'billed_cost_usd': None}}

위검색완료후현재후보의원문·실제입력을검토하여`source_review/retrieval_judgments.json`을작성한다. source확인없이아래집계셀을실행하지않는다. 임베딩외조건추출/답변API는0회다.

In [3]:
evaluation=R.evaluate_retrieval(64)
import pandas as pd
display(pd.DataFrame(evaluation['summary']))
display(pd.DataFrame(evaluation['factorial_contrasts']))

,profile,mode,group,questions,logical_rows,complete_evidence_macro,hit_at3_macro,mrr_at3_macro,hit_at3_upper_macro,mrr_at3_upper_macro
0,card_page_section_benefit,SEQ_new,explicit,30,90,0.866667,1.000000,0.977778,1.0,1.000000
1,card_page_section_benefit,SEQ_new,general,8,24,0.875000,NaN,NaN,NaN,NaN
2,card_page_section_benefit,SEQ_new,uncertain,2,6,NaN,NaN,NaN,NaN,NaN
3,card_page_section_benefit,SEQ_old,explicit,30,90,0.866667,1.000000,0.977778,1.0,1.000000
4,card_page_section_benefit,SEQ_old,general,8,24,0.875000,NaN,NaN,NaN,NaN
5,card_page_section_benefit,SEQ_old,uncertain,2,6,NaN,NaN,NaN,NaN,NaN
6,card_page_section_benefit,U_new,explicit,30,90,0.866667,1.000000,0.977778,1.0,1.000000
7,card_page_section_benefit,U_new,general,8,24,0.875000,NaN,NaN,NaN,NaN
8,card_page_section_benefit,U_new,uncertain,2,6,NaN,NaN,NaN,NaN,NaN
9,card_page_section_benefit,U_old,explicit,30,90,0.866667,1.000000,0.977778,1.0,1.000000
10,card_page_section_benefit,U_old,general,8,24,0.875000,NaN,NaN,NaN,NaN
11,card_page_section_benefit,U_old,uncertain,2,6,NaN,NaN,NaN,NaN,NaN
12,parent_child_bundle,SEQ_new,explicit,30,90,0.633333,0.966667,0.961111,1.0,0.972222
13,parent_child_bundle,SEQ_new,general,8,24,0.250000,NaN,NaN,NaN,NaN
14,parent_child_bundle,SEQ_new,uncertain,2,6,NaN,NaN,NaN,NaN,NaN
15,parent_child_bundle,SEQ_old,explicit,30,90,0.633333,0.966667,0.961111,1.0,0.972222
16,parent_child_bundle,SEQ_old,general,8,24,0.250000,NaN,NaN,NaN,NaN
17,parent_child_bundle,SEQ_old,uncertain,2,6,NaN,NaN,NaN,NaN,NaN
18,parent_child_bundle,U_new,explicit,30,90,0.433333,0.933333,0.900000,1.0,0.927778
19,parent_child_bundle,U_new,general,8,24,0.250000,NaN,NaN,NaN,NaN
20,parent_child_bundle,U_new,uncertain,2,6,NaN,NaN,NaN,NaN,NaN
21,parent_child_bundle,U_old,explicit,30,90,0.433333,0.933333,0.900000,1.0,0.927778
22,parent_child_bundle,U_old,general,8,24,0.250000,NaN,NaN,NaN,NaN
23,parent_child_bundle,U_old,uncertain,2,6,NaN,NaN,NaN,NaN,NaN

,profile,group,metric,scope_effect_u,scope_effect_seq,structured_effect_old,structured_effect_new,interaction
0,card_page_section_benefit,explicit,complete_evidence_macro,0.0,0.0,0.000000,0.000000,0.0
1,card_page_section_benefit,explicit,hit_at3_macro,0.0,0.0,0.000000,0.000000,0.0
2,card_page_section_benefit,explicit,mrr_at3_macro,0.0,0.0,0.000000,0.000000,0.0
3,card_page_section_benefit,general,complete_evidence_macro,0.0,0.0,0.000000,0.000000,0.0
4,parent_child_bundle,explicit,complete_evidence_macro,0.0,0.0,0.200000,0.200000,0.0
5,parent_child_bundle,explicit,hit_at3_macro,0.0,0.0,0.033333,0.033333,0.0
6,parent_child_bundle,explicit,mrr_at3_macro,0.0,0.0,0.061111,0.061111,0.0
7,parent_child_bundle,general,complete_evidence_macro,0.0,0.0,0.000000,0.000000,0.0